# Generated by Django 4.2.30 on 2026-04-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_gasto_cuui_autoincremental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Peso (g)'),
        ),
    ]
