# Generated by Django 4.2.30 on 2026-04-22 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_gasto_peso_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.cliente'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='cliente_texto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cliente (texto libre)'),
        ),
    ]
