# Generated by Django 4.2.30 on 2026-04-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_tarea_cliente_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente_texto',
        ),
    ]
