# Generated by Django 4.2.30 on 2026-04-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_pedido_quitar_cliente_texto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariopieza',
            options={'ordering': ['nombre'], 'verbose_name': 'Pieza', 'verbose_name_plural': 'Piezas'},
        ),
    ]
