# Generated by Django 4.2.30 on 2026-04-22 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_piezas_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Número de pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produccion.inventariopieza', verbose_name='Producto'),
        ),
    ]
