# Generated by Django 4.2.30 on 2026-04-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_pedido_producto_a_pieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('FDM', 'FDM'), ('Resina', 'Resina')], max_length=10, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PLA', 'PLA (Ácido Poliláctico)'), ('PETG', 'PETG (Tereftalato de Polietileno Glicol)'), ('TPU_TPE', 'TPU / TPE (Flexibles)'), ('ABS', 'ABS (Acrilonitrilo Butadieno Estireno)'), ('ASA', 'ASA (Acrilonitrilo Estireno Acrilato)'), ('Nylon', 'Nylon (Poliamida)'), ('PC', 'PC (Policarbonato)'), ('Especial', 'Filamentos Estéticos / Especiales (Seda, Fibra de carbono, Madera, etc.)'), ('R_Estandar', 'Resina Estándar'), ('R_WW', 'Resina Lavable con Agua (Water Washable)'), ('R_ABS', 'Resina Tipo ABS / Alta Resistencia (ABS-like / Tough)'), ('R_Flex', 'Resina Flexible / Elástica'), ('R_Clear', 'Resina Transparente (Clear)'), ('R_Castable', 'Resina Calcinable (Castable)'), ('R_HiTemp', 'Resina de Alta Temperatura'), ('R_Eco', 'Resina Basada en Plantas (Eco / Plant-based)'), ('R_Fast', 'Resina Rápida (Fast / Rapid)'), ('R_Dental', 'Resinas Dentales / Biocompatibles')], max_length=20, verbose_name='Tipo de material'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(blank=True, choices=[('FDM', 'FDM'), ('Resina', 'Resina')], max_length=10, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PLA', 'PLA (Ácido Poliláctico)'), ('PETG', 'PETG (Tereftalato de Polietileno Glicol)'), ('TPU_TPE', 'TPU / TPE (Flexibles)'), ('ABS', 'ABS (Acrilonitrilo Butadieno Estireno)'), ('ASA', 'ASA (Acrilonitrilo Estireno Acrilato)'), ('Nylon', 'Nylon (Poliamida)'), ('PC', 'PC (Policarbonato)'), ('Especial', 'Filamentos Estéticos / Especiales (Seda, Fibra de carbono, Madera, etc.)'), ('R_Estandar', 'Resina Estándar'), ('R_WW', 'Resina Lavable con Agua (Water Washable)'), ('R_ABS', 'Resina Tipo ABS / Alta Resistencia (ABS-like / Tough)'), ('R_Flex', 'Resina Flexible / Elástica'), ('R_Clear', 'Resina Transparente (Clear)'), ('R_Castable', 'Resina Calcinable (Castable)'), ('R_HiTemp', 'Resina de Alta Temperatura'), ('R_Eco', 'Resina Basada en Plantas (Eco / Plant-based)'), ('R_Fast', 'Resina Rápida (Fast / Rapid)'), ('R_Dental', 'Resinas Dentales / Biocompatibles')], max_length=20, verbose_name='Tipo de material'),
        ),
    ]
