# Generated by Django 4.2.30 on 2026-04-22 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_gasto_insumo_categoria_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de material',
                'verbose_name_plural': 'Tipos de material',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='tipo',
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Material')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='produccion.tipomaterial', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['tipo__nombre', 'nombre'],
                'unique_together': {('nombre', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produccion.material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produccion.material', verbose_name='Material'),
        ),
    ]
