# Generated by Django 4.2.30 on 2026-04-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0012_datos_tipos_materiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariopieza',
            name='archivo_3mf',
            field=models.FileField(blank=True, null=True, upload_to='piezas/3mf/', verbose_name='Archivo 3MF'),
        ),
        migrations.AddField(
            model_name='inventariopieza',
            name='url_referencia',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de referencia'),
        ),
    ]
