# Generated by Django 4.2.30 on 2026-04-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0013_pieza_archivo_3mf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariopieza',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='piezas/imagenes/', verbose_name='Imagen de la pieza'),
        ),
    ]
