# Generated by Django 4.2.30 on 2026-04-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0016_venta_rediseno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.RemoveField(
            model_name='venta',
            name='pedido',
        ),
        migrations.AddField(
            model_name='venta',
            name='pedidos',
            field=models.ManyToManyField(blank=True, related_name='ventas', to='produccion.pedido', verbose_name='Pedidos'),
        ),
    ]
