# Generated by Django 4.2.30 on 2026-04-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0018_empresa_multitenancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
