# Generated by Django 4.2.30 on 2026-04-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0019_venta_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Precio (COP)'),
        ),
    ]
