# Generated by Django 4.2.30 on 2026-04-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0020_insumo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='consumo_promedio_kw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Consumo promedio (kW)'),
        ),
    ]
