# Generated by Django 4.2.30 on 2026-04-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0025_pedido_figura'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produccion.insumo', verbose_name='Material (insumo)')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='produccion.pedido', verbose_name='Pedido')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.inventariopieza', verbose_name='Pieza')),
            ],
            options={
                'verbose_name': 'Material por pieza',
                'verbose_name_plural': 'Materiales por pieza',
                'ordering': ['pieza__nombre'],
                'unique_together': {('pedido', 'pieza')},
            },
        ),
    ]
