# Generated by Django 4.2.30 on 2026-04-28 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0026_pedido_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='material',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pieza',
        ),
    ]
