# Generated by Django 4.2.30 on 2026-04-28 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0027_pedido_solo_figura'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurapieza',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produccion.insumo', verbose_name='Insumo / Material'),
        ),
    ]
