# Generated by Django 4.2.30 on 2026-05-01 03:40

import apps.produccion.models.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0031_imagen_procesada_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figuraimagen',
            name='imagen',
            field=models.ImageField(upload_to=apps.produccion.models.upload_paths.upload_figura_imagen, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='figuraimagen',
            name='imagen_procesada',
            field=models.ImageField(blank=True, null=True, upload_to=apps.produccion.models.upload_paths.upload_figura_procesada, verbose_name='Imagen IA (estudio)'),
        ),
        migrations.AlterField(
            model_name='inventariopieza',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.produccion.models.upload_paths.upload_inventario_imagen, verbose_name='Imagen de la pieza'),
        ),
        migrations.AlterField(
            model_name='inventariopieza',
            name='imagen_procesada',
            field=models.ImageField(blank=True, null=True, upload_to=apps.produccion.models.upload_paths.upload_inventario_procesada, verbose_name='Imagen IA (estudio)'),
        ),
        migrations.AlterField(
            model_name='piezaimagen',
            name='imagen',
            field=models.ImageField(upload_to=apps.produccion.models.upload_paths.upload_pieza_imagen, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='piezaimagen',
            name='imagen_procesada',
            field=models.ImageField(blank=True, null=True, upload_to=apps.produccion.models.upload_paths.upload_pieza_procesada, verbose_name='Imagen IA (estudio)'),
        ),
    ]
