# Generated by Django 4.2.30 on 2026-06-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0032_upload_paths_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='archivo_3mf',
            field=models.FileField(blank=True, null=True, upload_to='figuras/3mf/', verbose_name='Archivo 3MF'),
        ),
    ]
