# Generated by Django 4.2.30 on 2026-06-04 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produccion', '0033_figura_archivo_3mf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseno3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('imagen_original', models.ImageField(upload_to='disenos3d/imagenes/', verbose_name='Imagen de referencia')),
                ('model_version', models.CharField(default='P1-20260311', max_length=50, verbose_name='Versión del modelo')),
                ('formato', models.CharField(choices=[('glb', 'GLB (recomendado)'), ('fbx', 'FBX'), ('obj', 'OBJ'), ('stl', 'STL'), ('usdz', 'USDZ')], default='glb', max_length=10, verbose_name='Formato de salida')),
                ('texture', models.BooleanField(default=True, verbose_name='Textura')),
                ('pbr', models.BooleanField(default=True, verbose_name='PBR (físicamente realista)')),
                ('face_limit', models.PositiveIntegerField(default=20000, verbose_name='Límite de polígonos')),
                ('texture_alignment', models.CharField(choices=[('original_image', 'Imagen original'), ('geometry', 'Geometría')], default='original_image', max_length=30, verbose_name='Alineación de textura')),
                ('orientation', models.CharField(choices=[('align_image', 'Alinear con imagen'), ('default', 'Por defecto')], default='align_image', max_length=30, verbose_name='Orientación')),
                ('enable_image_autofix', models.BooleanField(default=True, verbose_name='Corrección automática de imagen')),
                ('prompt', models.TextField(blank=True, verbose_name='Prompt (descripción 3D)')),
                ('analisis_ia', models.JSONField(blank=True, null=True, verbose_name='Análisis Claude')),
                ('tripo_task_id', models.CharField(blank=True, max_length=120, verbose_name='ID de tarea Tripo')),
                ('tripo_image_token', models.CharField(blank=True, max_length=300, verbose_name='Token imagen Tripo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('progreso', models.PositiveSmallIntegerField(default=0, verbose_name='Progreso (%)')),
                ('error_mensaje', models.TextField(blank=True, verbose_name='Error')),
                ('archivo_modelo', models.FileField(blank=True, null=True, upload_to='disenos3d/modelos/', verbose_name='Modelo 3D')),
                ('url_descarga_tripo', models.URLField(blank=True, max_length=500, verbose_name='URL descarga Tripo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disenos_3d', to='produccion.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Diseño 3D',
                'verbose_name_plural': 'Diseños 3D',
                'ordering': ['-creado_en'],
            },
        ),
    ]
