# Generated by Django 4.2.30 on 2026-07-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0034_diseno3d'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFigura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Categoría')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_figura', to='produccion.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoría de figura',
                'verbose_name_plural': 'Categorías de figura',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='figura',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figuras', to='produccion.categoriafigura', verbose_name='Categoría'),
        ),
    ]
