# Generated by Django 4.2.30 on 2026-07-16 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0036_categoriafigura_permisos_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='figuras', to='produccion.categoriafigura', verbose_name='Categorías'),
        ),
        migrations.AlterField(
            model_name='figura',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figuras_categoria_legacy', to='produccion.categoriafigura', verbose_name='Categoría (legacy)'),
        ),
    ]
