# Generated by Django 4.2.30 on 2026-07-16 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0038_migrar_categoria_a_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figura',
            name='categoria',
        ),
    ]
