# Generated by Django 4.2.30 on 2026-07-16 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0039_remove_figura_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaFigura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas_figura', to='produccion.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Etiqueta de figura',
                'verbose_name_plural': 'Etiquetas de figura',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='figura',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='figuras', to='produccion.etiquetafigura', verbose_name='Etiquetas'),
        ),
    ]
