# Generated by Django 4.2.30 on 2026-07-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0041_etiquetafigura_permisos_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuraimagen',
            name='ia_error',
            field=models.TextField(blank=True, default='', verbose_name='Error de procesamiento IA'),
        ),
        migrations.AddField(
            model_name='inventariopieza',
            name='ia_error',
            field=models.TextField(blank=True, default='', verbose_name='Error de procesamiento IA'),
        ),
        migrations.AddField(
            model_name='piezaimagen',
            name='ia_error',
            field=models.TextField(blank=True, default='', verbose_name='Error de procesamiento IA'),
        ),
    ]
