# Generated by Django 4.2.30 on 2026-07-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0042_figuraimagen_ia_error_inventariopieza_ia_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuraimagen',
            name='mostrar_imagen_ia',
            field=models.BooleanField(default=True, help_text='Si está marcado y hay imagen IA generada, el carrusel público muestra la imagen IA. Si está desmarcado, muestra siempre la imagen normal.', verbose_name='Usar IA en carrusel'),
        ),
    ]
