# Generated by Django 4.2.30 on 2026-07-29 17:51

from django.db import migrations, models


def _copiar_valor_anterior(apps, schema_editor):
    """Preserva la elección previa: mostrar_imagen_ia=True -> 'ia', False -> 'normal'."""
    FiguraImagen = apps.get_model('produccion', 'FiguraImagen')
    FiguraImagen.objects.filter(mostrar_imagen_ia=True).update(modo_carrusel='ia')
    FiguraImagen.objects.filter(mostrar_imagen_ia=False).update(modo_carrusel='normal')


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0043_figuraimagen_mostrar_imagen_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuraimagen',
            name='modo_carrusel',
            field=models.CharField(choices=[('ia', 'Solo IA'), ('normal', 'Solo original'), ('ambas', 'Ambas')], default='ia', help_text='Solo IA: muestra la imagen IA si existe (si no, cae a la original). Solo original: muestra siempre la imagen normal. Ambas: muestra las dos como fotos separadas en el carrusel.', max_length=10, verbose_name='Mostrar en carrusel'),
        ),
        migrations.RunPython(_copiar_valor_anterior, _noop),
        migrations.RemoveField(
            model_name='figuraimagen',
            name='mostrar_imagen_ia',
        ),
    ]
