# Generated by Django 4.2.30 on 2026-07-29 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0044_remove_figuraimagen_mostrar_imagen_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión asociado a este cliente.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comisión (%)'),
        ),
    ]
