# Generated by Django 4.2.30 on 2026-07-30 02:10

from django.db import migrations, models
import django.db.models.deletion


def _migrar_archivos_existentes(apps, schema_editor):
    """Convierte el archivo_3mf único de cada figura en su primer
    FiguraArchivo3MF, sin perder el archivo ya subido a Drive."""
    Figura = apps.get_model('produccion', 'Figura')
    FiguraArchivo3MF = apps.get_model('produccion', 'FiguraArchivo3MF')
    for figura in Figura.objects.exclude(archivo_3mf='').exclude(archivo_3mf__isnull=True):
        FiguraArchivo3MF.objects.create(
            figura=figura,
            archivo=figura.archivo_3mf.name,
            orden=0,
        )


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0045_cliente_comision'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiguraArchivo3MF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='figuras/3mf/', verbose_name='Archivo 3MF')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre / descripción')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('figura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_3mf', to='produccion.figura', verbose_name='Figura')),
            ],
            options={
                'verbose_name': 'Archivo 3MF de figura',
                'verbose_name_plural': 'Archivos 3MF de figura',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.RunPython(_migrar_archivos_existentes, _noop),
        migrations.RemoveField(
            model_name='figura',
            name='archivo_3mf',
        ),
    ]
