# Generated by Django 4.2.30 on 2026-08-20 02:58

import apps.produccion.models.upload_paths
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0047_figuraarchivo3mf_permisos_maker'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiguraTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: "Para NES", "Para Super Nintendo".', max_length=100, verbose_name='Nombre del tipo')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción / notas')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('figura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='produccion.figura', verbose_name='Figura')),
            ],
            options={
                'verbose_name': 'Tipo de figura',
                'verbose_name_plural': 'Tipos de figura',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FiguraColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del color')),
                ('color_hex', models.CharField(blank=True, help_text='Opcional, solo para mostrar una muestra. Ej: #FF6B35', max_length=7, verbose_name='Color (hex)')),
                ('imagen', models.ImageField(upload_to=apps.produccion.models.upload_paths.upload_figura_color, verbose_name='Imagen de este color')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('figura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores', to='produccion.figura', verbose_name='Figura')),
            ],
            options={
                'verbose_name': 'Color de figura',
                'verbose_name_plural': 'Colores de figura',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
