# Generated by Django 4.2.30 on 2026-08-20 03:18

import apps.produccion.models.upload_paths
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0048_figuratipo_figuracolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuratipo',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Se muestra en el carrusel de imágenes de la figura.', null=True, upload_to=apps.produccion.models.upload_paths.upload_figura_tipo, verbose_name='Imagen de este tipo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='produccion.figuracolor', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='produccion.figuratipo', verbose_name='Tipo'),
        ),
    ]
