# Generated by Django 4.2.30 on 2026-08-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0049_figuratipo_imagen_pedido_color_pedido_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='categorias_visibles',
            field=models.ManyToManyField(blank=True, help_text='Catálogo público (enlace con ?cliente=): si no eliges ninguna, se muestran todas las categorías.', related_name='clientes_visibles', to='produccion.categoriafigura', verbose_name='Categorías visibles para este cliente'),
        ),
    ]
