# Generated by Django 4.2.30 on 2026-08-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0050_cliente_categorias_visibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(blank=True, help_text='Hash de la contraseña de acceso al portal del catálogo. Se define desde el formulario de edición.', max_length=128, verbose_name='Contraseña (portal del cliente)'),
        ),
    ]
