# Generated by Django 4.2.30 on 2026-08-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0051_cliente_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(blank=True, help_text='Se completa solo cuando el pedido viene del checkout del catálogo público.', verbose_name='Dirección de entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_recibe',
            field=models.CharField(blank=True, help_text='Se completa solo cuando el pedido viene del checkout del catálogo público.', max_length=255, verbose_name='Nombre de quien recibe'),
        ),
    ]
