# Generated by Django 4.2.30 on 2026-08-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0054_tarea_trigger_sqlite_after_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='color',
            field=models.CharField(blank=True, help_text='Color del material comprado (ej. color del filamento).', max_length=7, verbose_name='Color'),
        ),
    ]
