# Generated by Django 4.2.30 on 2026-08-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0055_gasto_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='color',
            field=models.CharField(blank=True, help_text='Se toma del Gasto que originó este insumo.', max_length=7, verbose_name='Color'),
        ),
    ]
